// The Jenkinsfile for the Windows Development Builds pipeline.

node("idps-windows-node") {
    checkout scm
    pipelineModule = load "jenkins/pipeline.groovy"
    pipelineModule.run_all("windows")
}
